import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Providers from "@/providers/themeProvider";


const josefin = Josefin_Sans({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${josefin.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Providers>

          <Navbar />

          <main className="flex-grow">
            {children}
          </main>

          <Footer />

        </Providers>

        <ToastContainer />

      </body>
    </html>
  );
}